#!/usr/bin/env bash
# Automatizing the nginx configuration
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "52i \\\tadd_header X-Served-By $HOSTNAME always;" /etc/nginx/nginx.conf
sudo service nginx restart
